/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package travelnow.Frame;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import static java.time.LocalDateTime.now;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumnModel;
import net.proteanit.sql.DbUtils;
import travelnow.Controller.UserController;
import travelnow.Helper.Helper;
import travelnow.Model.MainModel;

/**
 *
 * @author user
 */
public class Bookings extends javax.swing.JFrame {
	
	MainModel model = new MainModel();
	UserController controller = new UserController();
    String usersID;
	String bookingsID;
    Helper helper = new Helper();
    ResultSet rs;
	public String username;
	public String password;
	
	public void getAllData(){
        this.rs = controller.Bookings(this.usersID);
        loadTable(this.rs);
    }
    
    public void loadTable(ResultSet rs){
        tb_bookings.setModel(DbUtils.resultSetToTableModel(rs));
		
		TableColumnModel tcm = tb_bookings.getColumnModel();
		tcm.getColumn(0).setHeaderValue("Nomor Pesanan");
		tcm.getColumn(1).setHeaderValue("Pengguna");
		tcm.getColumn(2).setHeaderValue("Hotel");
		tcm.getColumn(3).setHeaderValue("Paket");
		tcm.getColumn(4).setHeaderValue("Paket Negara");
		tcm.getColumn(5).setHeaderValue("Estimasi perjalanan");
		tcm.getColumn(6).setHeaderValue("Jumlah orang");
		tcm.getColumn(7).setHeaderValue("Total Harga");
		tcm.getColumn(8).setHeaderValue("Tanggal Keberangkatan");
		tcm.getColumn(9).setHeaderValue("Tanggal Dihapus");
    }
	
	/**
	 * Creates new form Bookings
	 * @param usersID
	 * @throws java.sql.SQLException
	 */
	public Bookings(String usersID) throws SQLException {
		initComponents();
		setLocationRelativeTo(this);
		this.usersID = usersID;
		getAllData();
		btn_cancel.setEnabled(false);
		username = controller.username(username, usersID);
		password = controller.password(password, usersID);
	}

	private Bookings() {
		throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_bookings = new javax.swing.JTable();
        btn_back = new javax.swing.JToggleButton();
        btn_cancel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        tb_bookings.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_bookings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_bookingsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_bookings);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(60, 90, 483, 240);

        btn_back.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_back.setText("< Back");
        btn_back.setToolTipText("");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        jPanel1.add(btn_back);
        btn_back.setBounds(520, 360, 70, 33);

        btn_cancel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_cancel.setText("Cancel Bookings");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cancel);
        btn_cancel.setBounds(240, 340, 124, 33);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/travelnow/Frame/Untitled design (7).png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 600, 400);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        // TODO add your handling code here:
		LocalDateTime deleted_at = now();
		try {        
        boolean result = controller.delete(deleted_at, bookingsID);
        if(result){
            JOptionPane.showMessageDialog(null, "Berhasil Menghapus Data");
			getAllData();
        }
        else{
            JOptionPane.showMessageDialog(null, "Gagal Menghapus Data");
        }
		} catch (Exception ex) {
            System.err.println(ex.getMessage());
        }
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void tb_bookingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_bookingsMouseClicked
        // TODO add your handling code here:
		try {
			String id = helper.getValueRows(tb_bookings,0);
			 
            btn_cancel.setEnabled(true);
            
            this.bookingsID = id;
            
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_tb_bookingsMouseClicked

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
		try {
			// TODO add your handling code here:
			User user = new User(username, password);
			this.setVisible(false);
			user.setVisible(true);
			dispose();
		} catch (SQLException ex) {
			Logger.getLogger(Bookings.class.getName()).log(Level.SEVERE, null, ex);
		}
    }//GEN-LAST:event_btn_backActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Bookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Bookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Bookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Bookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Bookings().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_back;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_bookings;
    // End of variables declaration//GEN-END:variables
}
