/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package travelnow.Frame;

import java.sql.ResultSet;
import java.time.LocalDateTime;
import static java.time.LocalDateTime.now;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumnModel;
import net.proteanit.sql.DbUtils;
import travelnow.Controller.AdminController;
import travelnow.Helper.Helper;
import travelnow.Model.MainModel;

/**
 *
 * @author HP
 */
public class Packet extends javax.swing.JFrame {
    MainModel model = new MainModel();
    AdminController controller = new AdminController();
    Helper helper = new Helper();
    ResultSet rs;
    String id;
	
	public void search (String type, String query){
        try {
            if(query.isEmpty()){
                this.rs=controller.get_packet();
            }
            else if (type.equals("name")&& !query.isEmpty()){
                this.rs = controller.showByNamePackets(query);
            }
            
            loadtable(this.rs);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * Creates new form Packet
     */
    public Packet() {
        initComponents();
        getAllData();
        clear();
        setLocationRelativeTo(this);
    }
    
    public void getAllData() {
        this.rs = controller.get_packet();
        loadtable(this.rs);
    }
    
    public void loadtable(ResultSet rs) {
        tb_packet.setModel(DbUtils.resultSetToTableModel(rs));
		
		TableColumnModel tcm = tb_packet.getColumnModel();
		tcm.getColumn(0).setHeaderValue("ID Paket");
		tcm.getColumn(1).setHeaderValue("Harga Paket");
		tcm.getColumn(2).setHeaderValue("Deskripsi Paket");
		tcm.getColumn(3).setHeaderValue("Nama Paket");
		tcm.getColumn(4).setHeaderValue("Tanggal Dihapus");
    }
    
    public void clear() {
        tf_name.setText("");
        tf_price.setText("");
        tf_description.setText("");
        
        btn_update.setEnabled(false);
        btn_delete.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_packet = new javax.swing.JTable();
        tf_search = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btn_home = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_name = new javax.swing.JTextField();
        tf_price = new javax.swing.JTextField();
        tf_description = new javax.swing.JTextField();
        btn_add = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        tb_packet.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tb_packet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_packet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_packetMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_packet);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(330, 100, 460, 290);

        tf_search.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(tf_search);
        tf_search.setBounds(330, 70, 160, 20);

        btn_search.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_search.setText("Search by Name");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });
        jPanel1.add(btn_search);
        btn_search.setBounds(500, 65, 140, 25);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel5.setText("Search");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(330, 40, 60, 21);

        btn_home.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_home.setText("Home");
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });
        jPanel1.add(btn_home);
        btn_home.setBounds(10, 360, 70, 30);

        btn_delete.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        jPanel1.add(btn_delete);
        btn_delete.setBounds(220, 230, 80, 30);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setText("Packets List");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(110, 30, 110, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Packet Name :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 90, 90, 20);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Price :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 120, 100, 20);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Description :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 150, 100, 17);

        tf_name.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(tf_name);
        tf_name.setBounds(130, 90, 170, 20);

        tf_price.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(tf_price);
        tf_price.setBounds(130, 120, 170, 20);

        tf_description.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(tf_description);
        tf_description.setBounds(130, 150, 170, 20);

        btn_add.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_add.setText("Add");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        jPanel1.add(btn_add);
        btn_add.setBounds(130, 190, 80, 30);

        btn_update.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        jPanel1.add(btn_update);
        btn_update.setBounds(220, 190, 80, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/travelnow/Frame/Untitled design (5).png"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, 0, 800, 400);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
        try {
        String price = tf_price.getText();
        String description = tf_description.getText();
        String name = tf_name.getText();
        
        model.setPacket_price(price);
        model.setPacket_description(description);
        model.setPacket_name(name);
        
        Boolean result = controller.input_packet(model);
        if (result) {
            JOptionPane.showMessageDialog(null, "New Packet has been Insert!");
            getAllData();
        }
        else {
            JOptionPane.showMessageDialog(null, "Insert Failed!");
        }
        clear();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
        try {
            String name = tf_name.getText();
            String price = tf_price.getText();
            String description = tf_description.getText();
            
            model.setPacket_name(name);
            model.setPacket_price(price);
            model.setPacket_description(description);
            
            Boolean result = controller.update_packet(id, model);
            if (result) {
                JOptionPane.showMessageDialog(null, "Update Success!");
            }
            else {
                JOptionPane.showMessageDialog(null, "Update Failed!");
            }
            clear();
            getAllData();
        } 
        catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void tb_packetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_packetMouseClicked
        // TODO add your handling code here:
        try {
            String id = helper.getValueRows(tb_packet, 0);
            String price = helper.getValueRows(tb_packet, 1);
            String description = helper.getValueRows(tb_packet, 2);
            String name = helper.getValueRows(tb_packet, 3);
            
            btn_update.setEnabled(true);
            btn_delete.setEnabled(true);
            this.id = id;
            tf_price.setText(price);
            tf_description.setText(description);
            tf_name.setText(name);
        } 
        catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_tb_packetMouseClicked

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
        // TODO add your handling code here:
        Admin admin = new Admin(id, id);
        admin.setVisible(true);
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_btn_homeActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
		LocalDateTime deleted_at = now();
		try {        
        boolean result = controller.deletePackets(deleted_at, id);
        if(result){
            JOptionPane.showMessageDialog(null, "Berhasil Menghapus Data");
			getAllData();
        }
        else{
            JOptionPane.showMessageDialog(null, "Gagal Menghapus Data");
        }
		} catch (Exception ex) {
            System.err.println(ex.getMessage());
        }
        
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        // TODO add your handling code here:
		search("name", tf_search.getText());
    }//GEN-LAST:event_btn_searchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Packet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Packet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Packet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Packet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Packet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_home;
    private javax.swing.JButton btn_search;
    private javax.swing.JButton btn_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_packet;
    private javax.swing.JTextField tf_description;
    private javax.swing.JTextField tf_name;
    private javax.swing.JTextField tf_price;
    private javax.swing.JTextField tf_search;
    // End of variables declaration//GEN-END:variables
}
