/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package travelnow.Frame;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import travelnow.Controller.UserController;
import travelnow.Helper.Helper;
import travelnow.Model.MainModel;

/**
 *
 * @author user
 */
public class Passengers extends javax.swing.JFrame {
	MainModel model = new MainModel();
	UserController controller = new UserController();
	Helper helper = new Helper();
	ResultSet rs;
	String passengersID;
	String usersID;
	String bookingsID;
	int counts;
	int count = 0;
	int total;
	String passengers;
	
	/**
	 * Creates new form Passengers
	 * @param bookingsID
	 * @param passengers
	 * @throws java.sql.SQLException
	 */
	public Passengers(String bookingsID, String passengers) throws SQLException {
		initComponents();
		setLocationRelativeTo(this);
		this.count = controller.count(bookingsID);
		tf_bookings.setText(bookingsID);
		tf_bookings.setEditable(false);
		this.passengers = passengers;
	}
	
	public void clear(){
		tf_first.setText("");
		tf_last.setText("");
		tf_email.setText("");
		tf_phone.setText("");
	}
	
	public void limit(String passengers) {
		int passenger = Integer.parseInt(passengers);
		this.count = this.count + 1;
		if (this.count >= passenger) {
			btn_submit.setEnabled(false);
			JOptionPane.showMessageDialog(null, "You've reach the limit");
		} else {
			JOptionPane.showMessageDialog(null, "You still need to input your passengers data");
		}
	}

	private Passengers() {
		throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_bookings = new javax.swing.JTextField();
        tf_first = new javax.swing.JTextField();
        tf_last = new javax.swing.JTextField();
        tf_email = new javax.swing.JTextField();
        tf_phone = new javax.swing.JTextField();
        btn_submit = new javax.swing.JToggleButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        jButton1.setText("Log Out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(340, 360, 77, 32);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Passengers Details");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(150, 30, 260, 60);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID Bookings :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(80, 120, 150, 20);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("First Name :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(80, 180, 150, 20);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Last Name :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(80, 230, 150, 20);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("E-mail Address :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(80, 270, 150, 20);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Phone Number :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(80, 320, 150, 20);
        jPanel1.add(tf_bookings);
        tf_bookings.setBounds(240, 120, 180, 30);
        jPanel1.add(tf_first);
        tf_first.setBounds(240, 180, 180, 30);
        jPanel1.add(tf_last);
        tf_last.setBounds(240, 230, 180, 30);
        jPanel1.add(tf_email);
        tf_email.setBounds(240, 270, 180, 30);
        jPanel1.add(tf_phone);
        tf_phone.setBounds(240, 320, 180, 30);

        btn_submit.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_submit.setText("Submit");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });
        jPanel1.add(btn_submit);
        btn_submit.setBounds(240, 360, 80, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/travelnow/Frame/Untitled design (6).png"))); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(0, 0, 500, 400);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        // TODO add your handling code here:
		try{
			limit(this.passengers);
			
			String first = tf_first.getText();
			String last = tf_last.getText();
			String email = tf_email.getText();
			String phone = tf_phone.getText();
			bookingsID = tf_bookings.getText();
			
			model.setBookingsID(bookingsID);
			model.setFirst(first);
			model.setLast(last);
			model.setEmail(email);
			model.setPhone(phone);
			
			boolean inputPassengers = controller.inputPassengers(model);
				
			if(inputPassengers){
				JOptionPane.showMessageDialog(null, "Your data have been submitted");
				clear();
			}
			else{
				JOptionPane.showMessageDialog(null, "Failed inputting your passengers data");
			}
		} catch (Exception ex){
			System.out.println(ex.getMessage());
		}
    }//GEN-LAST:event_btn_submitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
		Login login = new Login();
		this.setVisible(false);
		login.setVisible(true);
		dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Passengers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Passengers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Passengers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Passengers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Passengers().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_submit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tf_bookings;
    private javax.swing.JTextField tf_email;
    private javax.swing.JTextField tf_first;
    private javax.swing.JTextField tf_last;
    private javax.swing.JTextField tf_phone;
    // End of variables declaration//GEN-END:variables
}
