/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package travelnow.Frame;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import travelnow.Controller.MultiUserController;
import travelnow.Model.MainModel;

/**
 *
 * @author user
 */
public class Register extends javax.swing.JFrame {
	MainModel model = new MainModel();
	MultiUserController controller = new MultiUserController();
	ResultSet rs;
	
	/**
	 * Creates new form Register
	 */
	public Register() {
		initComponents();
		setLocationRelativeTo(this);
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf_first = new javax.swing.JTextField();
        tf_last = new javax.swing.JTextField();
        tf_address = new javax.swing.JTextField();
        tf_phone = new javax.swing.JTextField();
        tf_username = new javax.swing.JTextField();
        tf_email = new javax.swing.JTextField();
        tf_password = new javax.swing.JTextField();
        btn_submit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("First Name :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(80, 100, 160, 17);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Last Name :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(80, 130, 160, 17);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Address :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(80, 160, 160, 20);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Email Address :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(80, 190, 160, 20);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Phone Number :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(80, 220, 160, 20);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Username :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(80, 250, 160, 20);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Password :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(80, 280, 160, 20);
        jPanel1.add(tf_first);
        tf_first.setBounds(240, 100, 180, 20);
        jPanel1.add(tf_last);
        tf_last.setBounds(240, 130, 180, 20);
        jPanel1.add(tf_address);
        tf_address.setBounds(240, 160, 180, 20);
        jPanel1.add(tf_phone);
        tf_phone.setBounds(240, 220, 180, 20);
        jPanel1.add(tf_username);
        tf_username.setBounds(240, 250, 180, 20);
        jPanel1.add(tf_email);
        tf_email.setBounds(240, 190, 180, 20);
        jPanel1.add(tf_password);
        tf_password.setBounds(240, 280, 180, 20);

        btn_submit.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_submit.setText("Sign Up");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });
        jPanel1.add(btn_submit);
        btn_submit.setBounds(240, 320, 80, 30);

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton1.setText("< Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(410, 360, 80, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/travelnow/Frame/create acc bener.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(100, 0, 280, 120);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/travelnow/Frame/Untitled design (3).png"))); // NOI18N
        jLabel9.setText("jLabel9");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(0, 0, 500, 400);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        try{
			String first = tf_first.getText();
			String last = tf_last.getText();
			String address = tf_address.getText();
			String email = tf_email.getText();
			String phone = tf_phone.getText();
			String username = tf_username.getText();
			String password = tf_password.getText();
			
			model.setFirst(first);
			model.setLast(last);
			model.setAddress(address);
			model.setEmail(email);
			model.setPhone(phone);
			model.setUsername(username);
			model.setPassword(password);
			
			boolean register = controller.register(model);
			if(register){
				JOptionPane.showMessageDialog(null, "Welcome TravelNow, Please Log In");
			}
			else{
				JOptionPane.showMessageDialog(null, "Failed Submitting your Data");
			}
		} catch (Exception ex) {
			System.err.println(ex.getMessage());
		}
    }//GEN-LAST:event_btn_submitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
		Login login = new Login();
		this.setVisible(false);
		login.setVisible(true);
		dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Register().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_submit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tf_address;
    private javax.swing.JTextField tf_email;
    private javax.swing.JTextField tf_first;
    private javax.swing.JTextField tf_last;
    private javax.swing.JTextField tf_password;
    private javax.swing.JTextField tf_phone;
    private javax.swing.JTextField tf_username;
    // End of variables declaration//GEN-END:variables
}
