/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package travelnow.Frame;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import travelnow.Controller.UserController;
import javax.swing.JOptionPane;
import travelnow.Model.MainModel;

/**
 *
 * @author user
 */
public class User extends javax.swing.JFrame {
	ResultSet rs;
	MainModel model = new MainModel();
	UserController controller = new UserController();
	public String usersID;
	public String bookingsID;
	public String combo;
	public int totalPrice;
	
	/**
	 * Creates new form User
	 * @param username
	 * @param password
	 * @throws java.sql.SQLException
	 */
	
	public User(String username, String password) throws SQLException {
		initComponents();
		setLocationRelativeTo(this);
		usersID = controller.usersID(username, password, usersID);
		tf_usersid.setText(usersID);
		String getHotels = controller.getHotels(combo, cb_hotel);
		String getAirlines = controller.getAirlines(combo, cb_airlines);
		String getPackets = controller.getPackets(combo, cb_packet);
		tf_usersid.setEnabled(false);
		tf_price.setEnabled(false);
	}

	private User() {
		throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tf_usersid = new javax.swing.JTextField();
        btn_logout = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cb_hotel = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cb_packet = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cb_airlines = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        tf_estimation = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_price = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btn_submit = new javax.swing.JButton();
        btn_calculate = new javax.swing.JButton();
        btn_bookings = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        tf_passengers = new javax.swing.JTextField();
        dp_transaction = new org.jdesktop.swingx.JXDatePicker();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Costumer ID :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 10, 110, 20);
        jPanel1.add(tf_usersid);
        tf_usersid.setBounds(120, 10, 90, 30);

        btn_logout.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_logout.setText("Log Out");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        jPanel1.add(btn_logout);
        btn_logout.setBounds(710, 430, 80, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Hotels :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 170, 110, 20);

        jPanel1.add(cb_hotel);
        cb_hotel.setBounds(150, 170, 200, 26);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Packets :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 220, 110, 20);

        jPanel1.add(cb_packet);
        cb_packet.setBounds(150, 220, 202, 26);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Airlines :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 270, 110, 20);

        jPanel1.add(cb_airlines);
        cb_airlines.setBounds(150, 270, 202, 26);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Estimated Trip :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(400, 150, 140, 20);
        jPanel1.add(tf_estimation);
        tf_estimation.setBounds(540, 150, 180, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Total Price :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(400, 260, 140, 20);
        jPanel1.add(tf_price);
        tf_price.setBounds(540, 260, 180, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Departure Date :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(400, 300, 140, 20);

        btn_submit.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_submit.setText("Submit");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });
        jPanel1.add(btn_submit);
        btn_submit.setBounds(340, 330, 70, 30);

        btn_calculate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_calculate.setText("Calculate");
        btn_calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calculateActionPerformed(evt);
            }
        });
        jPanel1.add(btn_calculate);
        btn_calculate.setBounds(630, 220, 90, 33);

        btn_bookings.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_bookings.setText("Check your Bookings");
        btn_bookings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bookingsActionPerformed(evt);
            }
        });
        jPanel1.add(btn_bookings);
        btn_bookings.setBounds(290, 420, 170, 30);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Passengers :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(400, 190, 140, 20);
        jPanel1.add(tf_passengers);
        tf_passengers.setBounds(540, 190, 180, 30);
        jPanel1.add(dp_transaction);
        dp_transaction.setBounds(540, 300, 180, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/travelnow/Frame/welcometn.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 10, 800, 70);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setText("Pax");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(730, 180, 50, 17);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("Days");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(730, 150, 40, 20);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/travelnow/Frame/Untitled design (4).png"))); // NOI18N
        jLabel11.setText("Days");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(0, 0, 800, 470);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
		Login login = new Login();
		this.setVisible(false);
		login.setVisible(true);
		dispose();
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        // TODO add your handling code here:
		//INPUT DATA KE BOOKINGS
		try{
		String hotels = cb_hotel.getSelectedItem().toString();
		String airlines = cb_airlines.getSelectedItem().toString();
		String packets = cb_packet.getSelectedItem().toString();
		String estimation = tf_estimation.getText();
		String passengers = tf_passengers.getText();
		String price = tf_price.getText();
		Date date = dp_transaction.getDate();
		
		model.setHotels(hotels);
		model.setAirlines(airlines);
		model.setPackets(packets);
		model.setEstimation(estimation);
		model.setPassengers(passengers);
		model.setPrice(price);
		model.setTransactiondate(date);
		
		String hotelsID = controller.hotelsID(model, hotels);
		String airlinesID = controller.airlinesID(model, airlines);
		String packetsID = controller.packetsID(model, packets);
		
		String hotelsPrice = controller.hotelsPrice(model, hotelsID);
		String airlinesPrice = controller.airlinesPrice(model, airlinesID);
		String packetsPrice = controller.packetsPrice(model, packetsID);
		
		int totalPrice = controller.totalPrice(model, hotelsPrice, airlinesPrice, packetsPrice);
		
		boolean input = controller.input(model, usersID, hotelsID, airlinesID, packetsID, totalPrice);
		if(input){
			JOptionPane.showMessageDialog(null, "Your bookings Success");
			bookingsID = controller.bookingsID(model, totalPrice, bookingsID);
			Passengers framepassengers = new Passengers(bookingsID, passengers);
			this.setVisible(false);
			framepassengers.setVisible(true);
			dispose();
		}
		else{
			JOptionPane.showMessageDialog(null, "Your bookings Failed");
		}
		} catch (Exception ex) {
			System.out.println(ex.getMessage());
		}
    }//GEN-LAST:event_btn_submitActionPerformed
	
	
    private void btn_calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calculateActionPerformed
        // TODO add your handling code here:
		
		//PEMBERITAHUAN
		JOptionPane.showMessageDialog(null, "Jangan lupa untuk mengisi esti"
					+ "masi hari perjalanan anda untuk melakukan kalkulasi", "Alert", HEIGHT);
		
		//HANYA UNTUK MENUNJUKKAN HASIL KALKULASI, BELUM INPUT KE DATABASE
		try{
		String hotels = cb_hotel.getSelectedItem().toString();
		String airlines = cb_airlines.getSelectedItem().toString();
		String packets = cb_packet.getSelectedItem().toString();
		String estimation = tf_estimation.getText();
		String passengers = tf_passengers.getText();
		
		model.setHotels(hotels);
		model.setAirlines(airlines);
		model.setPackets(packets);
		model.setEstimation(estimation);
		model.setPassengers(passengers);
		
		String hotelsID = controller.hotelsID(model, hotels);
		String airlinesID = controller.airlinesID(model, airlines);
		String packetsID = controller.packetsID(model, packets);
		
		String hotelsPrice = controller.hotelsPrice(model, hotelsID);
		String airlinesPrice = controller.airlinesPrice(model, airlinesID);
		String packetsPrice = controller.packetsPrice(model, packetsID);
		
		int totalPrice = controller.totalPrice(model, hotelsPrice, airlinesPrice, packetsPrice);
		tf_price.setText(Integer.toString(totalPrice));
		} catch (Exception ex) {
			System.out.println(ex.getMessage());
		}
    }//GEN-LAST:event_btn_calculateActionPerformed

    private void btn_bookingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bookingsActionPerformed
		try {
			// TODO add your handling code here:
			Bookings bookings = new Bookings(usersID);
			this.setVisible(false);
			bookings.setVisible(true);
			dispose();
		} catch (SQLException ex) {
			Logger.getLogger(User.class.getName()).log(Level.SEVERE, null, ex);
		}
    }//GEN-LAST:event_btn_bookingsActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new User().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bookings;
    private javax.swing.JButton btn_calculate;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_submit;
    private javax.swing.JComboBox<String> cb_airlines;
    private javax.swing.JComboBox<String> cb_hotel;
    private javax.swing.JComboBox<String> cb_packet;
    private org.jdesktop.swingx.JXDatePicker dp_transaction;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tf_estimation;
    private javax.swing.JTextField tf_passengers;
    private javax.swing.JTextField tf_price;
    private javax.swing.JTextField tf_usersid;
    // End of variables declaration//GEN-END:variables
}
