/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package travelnow.Frame;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import travelnow.Controller.UserController;
import javax.swing.JOptionPane;
import travelnow.Model.MainModel;

/**
 *
 * @author user
 */
public class User extends javax.swing.JFrame {
	ResultSet rs;
	MainModel model = new MainModel();
	UserController controller = new UserController();
	public String usersID;
	public int totalPrice;
	
	/**
	 * Creates new form User
	 * @param username
	 * @param password
	 * @throws java.sql.SQLException
	 */
	
	public User(String username, String password) throws SQLException {
		initComponents();
		setLocationRelativeTo(this);
		usersID = controller.usersID(username, password, usersID);
		tf_usersid.setText(usersID);
		tf_usersid.setEnabled(false);
		tf_price.setEnabled(false);
	}

	private User() {
		throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_usersid = new javax.swing.JTextField();
        btn_logout = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cb_hotel = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cb_packet = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cb_airlines = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        tf_estimation = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_price = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btn_submit = new javax.swing.JButton();
        dp_transaction = new org.jdesktop.swingx.JXDatePicker();
        btn_calculate = new javax.swing.JButton();
        btn_bookings = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setText("Selamat datang di TravelNow");

        jLabel2.setText("Silahkan membuat pesanan");

        jLabel3.setText("Pemesan :");

        btn_logout.setText("Log Out");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        jLabel4.setText("Pilihan Hotel :");

        cb_hotel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Intercontinental Hotel", "Four Seasons Hotel", "RedDoorz Hotel" }));

        jLabel5.setText("Pilihan Paket :");

        cb_packet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tera", "Giga", "Mega" }));

        jLabel6.setText("Pilihan Maskapai :");

        cb_airlines.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kingdom", "Phylum", "Class" }));

        jLabel7.setText("Estimasi perjalanan :");

        jLabel8.setText("Total :");

        jLabel9.setText("Tanggal Keberangkatan :");

        btn_submit.setText("Submit");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });

        btn_calculate.setText("Calculate");
        btn_calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calculateActionPerformed(evt);
            }
        });

        btn_bookings.setText("Check your Bookings");
        btn_bookings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bookingsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dp_transaction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_usersid)
                            .addComponent(cb_hotel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb_packet, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb_airlines, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tf_estimation)
                            .addComponent(tf_price)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_submit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_bookings)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_calculate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(157, 157, 157))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_usersid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(cb_hotel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cb_packet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cb_airlines, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_estimation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_calculate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(dp_transaction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_submit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_logout)
                    .addComponent(btn_bookings))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
		Login login = new Login();
		this.setVisible(false);
		login.setVisible(true);
		dispose();
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        // TODO add your handling code here:
		//INPUT DATA KE BOOKINGS
		try{
		String hotels = cb_hotel.getSelectedItem().toString();
		String airlines = cb_airlines.getSelectedItem().toString();
		String packets = cb_packet.getSelectedItem().toString();
		String estimation = tf_estimation.getText();
		String price = tf_price.getText();
		Date date = dp_transaction.getDate();
		
		model.setHotels(hotels);
		model.setAirlines(airlines);
		model.setPackets(packets);
		model.setEstimation(estimation);
		model.setPrice(price);
		model.setTransactiondate(date);
		
		String hotelsID = controller.hotelsID(model, hotels);
		String airlinesID = controller.airlinesID(model, airlines);
		String packetsID = controller.packetsID(model, packets);
		
		String hotelsPrice = controller.hotelsPrice(model, hotelsID);
		String airlinesPrice = controller.airlinesPrice(model, airlinesID);
		String packetsPrice = controller.packetsPrice(model, packetsID);
		
		int totalPrice = controller.totalPrice(model, hotelsPrice, airlinesPrice, packetsPrice);
		
		boolean input = controller.input(model, usersID, hotelsID, airlinesID, packetsID, totalPrice);
		if(input){
			JOptionPane.showMessageDialog(null, "Pesanan anda berhasil");
		}
		else{
			JOptionPane.showMessageDialog(null, "Pesanan anda gagal");
		}
		} catch (Exception ex) {
			System.out.println(ex.getMessage());
		}
    }//GEN-LAST:event_btn_submitActionPerformed

    private void btn_calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calculateActionPerformed
        // TODO add your handling code here:
		
		//PEMBERITAHUAN
		JOptionPane.showMessageDialog(null, "Jangan lupa untuk mengisi esti"
					+ "masi hari perjalanan anda untuk melakukan kalkulasi", "Alert", HEIGHT);
		
		//HANYA UNTUK MENUNJUKKAN HASIL KALKULASI, BELUM INPUT KE DATABASE
		try{
		String hotels = cb_hotel.getSelectedItem().toString();
		String airlines = cb_airlines.getSelectedItem().toString();
		String packets = cb_packet.getSelectedItem().toString();
		String estimation = tf_estimation.getText();
		
		model.setHotels(hotels);
		model.setAirlines(airlines);
		model.setPackets(packets);
		model.setEstimation(estimation);
		
		String hotelsID = controller.hotelsID(model, hotels);
		String airlinesID = controller.airlinesID(model, airlines);
		String packetsID = controller.packetsID(model, packets);
		
		String hotelsPrice = controller.hotelsPrice(model, hotelsID);
		String airlinesPrice = controller.airlinesPrice(model, airlinesID);
		String packetsPrice = controller.packetsPrice(model, packetsID);
		
		int totalPrice = controller.totalPrice(model, hotelsPrice, airlinesPrice, packetsPrice);
		tf_price.setText(Integer.toString(totalPrice));
		} catch (Exception ex) {
			System.out.println(ex.getMessage());
		}
    }//GEN-LAST:event_btn_calculateActionPerformed

    private void btn_bookingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bookingsActionPerformed
		try {
			// TODO add your handling code here:
			Bookings bookings = new Bookings(usersID);
			this.setVisible(false);
			bookings.setVisible(true);
			dispose();
		} catch (SQLException ex) {
			Logger.getLogger(User.class.getName()).log(Level.SEVERE, null, ex);
		}
    }//GEN-LAST:event_btn_bookingsActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new User().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bookings;
    private javax.swing.JButton btn_calculate;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_submit;
    private javax.swing.JComboBox<String> cb_airlines;
    private javax.swing.JComboBox<String> cb_hotel;
    private javax.swing.JComboBox<String> cb_packet;
    private org.jdesktop.swingx.JXDatePicker dp_transaction;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField tf_estimation;
    private javax.swing.JTextField tf_price;
    private javax.swing.JTextField tf_usersid;
    // End of variables declaration//GEN-END:variables
}
